I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/phase1.rpy", line 30, in script
    show Galilean_1 Default "Good morning! Sorry to disturb you so early in the morning…" at left with easeinleft
Exception: Image 'Galilean_1 Default' does not accept attributes '"Good morning! Sorry to disturb you so early in the morning…"'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/phase1.rpy", line 30, in script
    show Galilean_1 Default "Good morning! Sorry to disturb you so early in the morning…" at left with easeinleft
  File "renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 742, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/transform.py", line 865, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'Galilean_1 Default' does not accept attributes '"Good morning! Sorry to disturb you so early in the morning…"'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
rai_farmville2 1.0
Fri Sep 16 18:38:07 2022
